version: "3"
services:

  redis:
    image: redis:latest
    container_name: redis
    networks:
      finapp-net:
    expose:
      - 6379
    volumes:
      - redis-storage:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]

  api:
    container_name: api
    image: jensklimke/finance:dev
    command: ["npm", "run", "start:api"]
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: ${API_PORT}
      VIRTUAL_HOST: ${API_HOST}
      LETSENCRYPT_HOST: ${API_HOST}
    ports:
      - "${API_PORT}:${API_PORT}"
    networks:
      finapp-net:
      jk-net:
    depends_on:
      - redis

  finapp:
    container_name: finapp
    image: jensklimke/finance:dev
    command: [ "npm", "run", "start:finapp" ]
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      VIRTUAL_HOST: ${APP_HOST}
      LETSENCRYPT_HOST: ${APP_HOST}
    networks:
      finapp-net:
      jk-net:
    depends_on:
      - api

volumes:
  redis-storage:
    external: true

networks:
  finapp-net:
  jk-net:
    external: true
