name: Checks

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout" # Download code from the repository
        uses: actions/checkout@v2 # Public action
        with:
          fetch-depth: 0 # Checkout all branches and tags

      - name: "Use NodeJS 14" # Setup node using version 14
        uses: actions/setup-node@v2 # Public action
        with:
          node-version: '17'

      - name: "Start Redis"
        uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: '6'

      - name: "Install dependencies"
        run: | # Install and link dependencies
          npm i
          npx lerna bootstrap

      - name: "Build"
        run: | 
          npm run build

      - name: "Run tests"
        run: |
          npm run test
        env:
          CI: true

